# Generated by Django 2.0.4 on 2018-05-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('lastupdate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
