# Generated by Django 2.0.4 on 2018-05-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemlist',
            old_name='quantity',
            new_name='price',
        ),
    ]
