# Generated by Django 2.0.4 on 2018-05-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20180511_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemlist',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='itemlist',
            old_name='price',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='itemlist',
            name='lastupdate',
        ),
    ]
