# Generated by Django 2.0.4 on 2018-05-15 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20180511_1221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemList',
            new_name='Items',
        ),
    ]
